export const modules=[
 {id:"entorno",label:"3–4 · Diagnóstico del entorno",short:"Entorno",chapter:"Cap. 3"},
 {id:"investigacion",label:"3–4 · Investigación y sesgos",short:"Investigación",chapter:"Cap. 4"},
 {id:"directorio",label:"3–4 · Simulador de directorio",short:"Directorio",chapter:"Casos 3–4"},
 {id:"cuantitativo",label:"3–4 · Aritmética de marketing",short:"Cálculos",chapter:"Laboratorio"},
 {id:"consumidor5",label:"5–6 · Caja negra del consumidor",short:"Consumidor",chapter:"Cap. 5"},
 {id:"decision5",label:"5–6 · Decisión y adopción",short:"Decisión",chapter:"Cap. 5"},
 {id:"negocios6",label:"5–6 · Mercados de negocios",short:"B2B",chapter:"Cap. 6"},
 {id:"compras6",label:"5–6 · Centro y proceso de compra",short:"Compras B2B",chapter:"Cap. 6"},
 {id:"tarjetas",label:"3–6 · Tarjetas de maestría",short:"Conceptos",chapter:"Cap. 3 a 6"}
];

const choice=(id,module,title,context,options,answer,explanation,meta={})=>({id,module,type:"choice",title,context,options,answer,explanation,...meta});
export const activities=[
 choice("e1","entorno","Aranceles al acero importado","Una ensambladora enfrenta un alza del 25% y riesgo de desabastecimiento.",["Micro · Intermediarios · Negociación","Macro · Político-legal · Adaptación","Macro · Tecnológico · Innovación","Micro · Público financiero · Negociación"],1,"Es macroentorno político-legal. La firma debe adaptarse, buscar fuentes locales y recalcular costos."),
 choice("e2","entorno","Derecho de anaquel","Walmart exige a una pyme de pastas un 8% adicional o reubicará sus productos.",["Macro · Económico · Adaptación","Micro · Intermediarios · Negociación","Macro · Cultural · Innovación","Micro · Competidores · Adaptación"],1,"Es un intermediario del microentorno: existe relación directa y margen para negociar volumen, rotación y canales."),
 choice("e3","entorno","Nuevas estructuras familiares","Crecen los hogares monoparentales y unipersonales; se estanca la demanda de heladeras familiares.",["Micro · Clientes · Negociación","Macro · Demográfico · Innovación proactiva","Macro · Natural · Adaptación","Micro · Competidores · Innovación"],1,"Es una transformación demográfica que invita a investigar y rediseñar la cartera hacia soluciones compactas."),
 choice("e4","entorno","Un fondo activista presiona","Un fondo adquiere 12% de las acciones y exige cancelar la inversión verde para elevar dividendos.",["Macro · Económico · Adaptación","Micro · Público financiero · Negociación","Macro · Político-legal · Adaptación","Micro · Proveedores · Innovación"],1,"Los accionistas integran los públicos financieros del microentorno. Corresponde negociar con evidencia de retorno y riesgo ESG."),
 choice("e5","entorno","Racionamiento industrial de agua","La contaminación de acuíferos obliga al municipio a reducir 40% el uso industrial de agua.",["Macro · Natural · Innovación proactiva","Micro · Proveedores · Negociación","Macro · Demográfico · Adaptación","Micro · Público local · Negociación"],0,"Es una fuerza del macroentorno natural. La respuesta proactiva incluye recirculación, ecoeficiencia y reducción de huella hídrica."),
 choice("e6","entorno","Un competidor SaaS cambia el mercado","Un rival reduce a la mitad el costo de implementación mediante suscripción mensual sin hardware inicial.",["Macro · Tecnológico · Adaptación","Micro · Competidores · Innovación proactiva","Micro · Intermediarios · Negociación","Macro · Económico · Adaptación"],1,"El rival es un actor del microentorno. Requiere revisar el modelo comercial, pricing por uso y ventajas de soporte."),
 choice("i1","investigacion","Red Bull: precio y canibalización","Se estudia lanzar agua vitaminizada a USD 2,80 sin dañar la lata clásica.",["Encuestas descriptivas en gimnasios","Exploración cualitativa y experimento causal en plazas comparables","Diez focus groups para fijar el precio"],1,"La fase cualitativa descubre ocasiones de uso; el experimento permite aislar canibalización y efecto de precio."),
 choice("i2","investigacion","Nielsen: 9.000 hogares","Finanzas afirma que 9.000 hogares no pueden representar a millones de habitantes.",["Aceptar un margen de error del 30%","Explicar muestreo probabilístico estratificado y error estándar","Reemplazarlo por encuestas telefónicas diarias"],1,"La precisión depende del diseño y del tamaño absoluto de la muestra, además del control de cobertura y no respuesta."),
 choice("i3","investigacion","Frito-Lay y neuromarketing","Las encuestas elogiaban un envase brillante, pero las ventas caían 12%.",["El brillo activaba dolor físico","El empaque despertaba culpa no verbalizada; se rediseñó mate","La biometría no produjo patrones útiles"],1,"La contradicción ilustra el valor —y los límites— de combinar declaraciones con observación biométrica."),
 choice("i4","investigacion","Una pregunta manipuladora","“Dado que nuestra marca lidera en calidad, ¿qué tan superior considera nuestro servicio?”",["Es técnicamente correcta","Es inductora; debe neutralizarse con escala equilibrada","Debe ser siempre abierta"],1,"Los adjetivos anticipan una conclusión y sesgan la respuesta. La redacción debe ser neutral y admitir todo el rango."),
 choice("d1","directorio","Target durante la recesión","Las ventas caen y la marca es percibida como cara. ¿Cómo equilibrar valor y diferenciación?",["Liquidar diseño y competir solo por precio","Mantener diseño, sumar compra frecuente y marca propia","Sostener precios altos con publicidad aspiracional"],1,"El rebalanceo hacia “pague menos” protege la diferenciación y aumenta frecuencia sin una guerra frontal de costos.",{kpis:["Ventas/tienda −10%","Walmart +5%","Imagen de precio: cara"]}),
 choice("d2","directorio","Harrah’s Total Rewards","La analítica muestra que 26% de clientes genera 82% de las utilidades.",["Concentrarse en grandes apostadores","CRM predictivo para jugadores frecuentes de tragamonedas"],1,"La fidelización basada en comportamiento produce ingresos más estables y permite recompensas oportunas.",{kpis:["40 M clientes","26% genera 82%","+24% gasto feliz"]}),
 choice("d3","directorio","Kellogg’s y evidencia publicitaria","El promedio observado fue 11%, pero se propone anunciar una mejora de hasta 20%.",["Publicar con aclaración pequeña","Descartar la afirmación y comunicar evidencia representativa"],1,"Elegir el extremo para representar el resultado general induce a error y expone a riesgo ético y regulatorio.",{kpis:["Claim +20%","Promedio 11%","Confianza en riesgo"]}),
 choice("d4","directorio","Crisis reputacional viral","Un cliente publica un video destruyendo su equipo tras una garantía rechazada.",["Demandar y forzar la baja del video","Disculpa, solución al cliente y auditoría del soporte"],1,"La respuesta repara el caso y aborda la causa raíz; la judicialización puede amplificar la crisis.",{kpis:["520.000 vistas","Boicot emergente","Riesgo Streisand"]}),
 {id:"q1",module:"cuantitativo",type:"number",title:"Tamaño de mercado pediátrico",context:"40.000 hogares × 60% con hijos × 50% de incidencia × USD 1.000 anuales.",question:"¿Cuál es el mercado anual estimado en USD?",answer:12000000,tolerance:0,explanation:"40.000 × 0,60 × 0,50 × 1.000 = USD 12.000.000."},
 {id:"q2",module:"cuantitativo",type:"number",title:"Brecha de gasto por experiencia",context:"Un cliente feliz aumenta 24% un gasto base de USD 500; uno decepcionado lo reduce 10%.",question:"¿Cuál es la diferencia de gasto entre ambos?",answer:170,tolerance:0,explanation:"USD 620 frente a USD 450: la brecha es USD 170 por visita."},
 {id:"q3",module:"cuantitativo",type:"number",title:"Utilidad por cliente clave",context:"De 40.000 clientes, 26% produce 82% de USD 10 millones en utilidades.",question:"¿Cuánta utilidad genera en promedio cada cliente clave?",answer:788,tolerance:1,explanation:"USD 8.200.000 / 10.400 clientes = aproximadamente USD 788 por cliente."}
];

// Capítulos 5 y 6 - edición suministrada por la cátedra.
activities.push(
 {id:"c5-1",module:"consumidor5",type:"matrix",title:"Dentro de la caja negra",context:"Una estudiante ve una campaña de una notebook, consulta reseñas de su grupo de referencia y decide esperar una promoción porque teme equivocarse.",fields:[{label:"Entrada",options:["estímulo de marketing","respuesta de compra","factor poscompra"]},{label:"Influencia dominante",options:["cultural","social","personal","psicológica"]},{label:"Salida observable",options:["preferencia y momento de compra","subcultura","motivación inconsciente"]}],answer:["estímulo de marketing","social","preferencia y momento de compra"],explanation:"El anuncio ingresa como estímulo, el grupo opera como influencia social y la espera se observa como respuesta de compra."},
 {id:"c5-2",module:"consumidor5",type:"matrix",title:"Radiografía de una compra Apple",context:"Un comprador elige un iPhone porque expresa quién es, sus amistades lo recomiendan y percibe que la interfaz es más sencilla.",fields:[{label:"Identidad",options:["cultura","autoconcepto","ocupación"]},{label:"Entorno cercano",options:["grupo de referencia","clase social","situación económica"]},{label:"Proceso interno",options:["percepción","familia","rol y estatus"]}],answer:["autoconcepto","grupo de referencia","percepción"],explanation:"El caso combina un factor personal —autoconcepto—, uno social —grupo— y uno psicológico —percepción selectiva—."},
 choice("c5-3","consumidor5","¿Qué tipo de conducta de compra?","Una pareja compara durante semanas marcas de automóviles costosos, percibe diferencias importantes y considera alto el riesgo.",["Compra habitual","Búsqueda de variedad","Compra compleja","Compra que reduce disonancia"],2,"Alta participación y diferencias importantes entre marcas caracterizan la conducta de compra compleja."),
 choice("c5-4","consumidor5","Cuando casi no hay diferencias","Una organización familiar contrata un servicio costoso, encuentra ofertas muy similares y luego busca argumentos que confirmen su elección.",["Compra compleja","Compra que reduce disonancia","Compra habitual","Búsqueda de variedad"],1,"La alta participación con pocas diferencias percibidas puede producir disonancia posterior."),
 {id:"c5-5",module:"consumidor5",type:"text",title:"Mapa de influencias Porsche",context:"Porsche sostiene que sus compradores ven el vehículo como una expresión de autoimagen y estilo de vida, no sólo como transporte.",prompt:"Construyan una explicación que conecte autoconcepto, estilo de vida, motivación y grupo de referencia.",rubric:["Distingue factor personal y psicológico","Conecta la marca con identidad","Explica una conducta observable"],explanation:"La marca funciona como símbolo del yo real o ideal y se refuerza socialmente."},
 {id:"c5-6",module:"decision5",type:"sequence",title:"El viaje de decisión",context:"Una persona detecta que necesita una computadora, busca información, compara alternativas, compra y evalúa la experiencia.",steps:["Reconocimiento de la necesidad","Búsqueda de información","Evaluación de alternativas"],answer:[0,1,2],explanation:"Estas son las tres primeras etapas; luego siguen decisión de compra y comportamiento posterior."},
 {id:"c5-7",module:"decision5",type:"allocation",title:"¿Dónde invertir para acelerar adopción?",context:"Una empresa lanza un dispositivo doméstico novedoso y debe distribuir su esfuerzo para reducir incertidumbre.",options:["Ventaja relativa y demostración","Compatibilidad y prueba","Observabilidad y referentes"],answer:0,prompt:"Distribuyan 100 puntos de inversión entre tres palancas de adopción.",explanation:"La adopción se acelera cuando la innovación ofrece ventaja relativa, compatibilidad, posibilidad de prueba, baja complejidad y resultados observables."},
 choice("c5-8","decision5","Categorías de adoptadores","Una clienta compra una innovación después de observar a referentes respetados, pero antes que la mayoría del mercado.",["Innovadora","Adoptadora temprana","Mayoría temprana","Mayoría tardía"],1,"Los adoptadores tempranos suelen ser líderes de opinión y legitiman la innovación ante otros."),
 {id:"c5-9",module:"decision5",type:"text",title:"Intervenir después de la compra",context:"Un cliente duda si eligió bien una notebook y presta atención a comentarios negativos sobre su marca.",prompt:"Diseñen una intervención poscompra que reduzca disonancia sin manipular al cliente.",rubric:["Reconoce la disonancia","Aporta evidencia y soporte","No oculta limitaciones"],explanation:"El seguimiento, la asistencia y la confirmación honesta de valor reducen disonancia y favorecen recompra."},
 {id:"c6-1",module:"negocios6",type:"matrix",title:"Del consumidor al proveedor",context:"Cae la venta de computadoras hogareñas y, semanas después, los fabricantes reducen pedidos de microprocesadores.",fields:[{label:"Tipo de demanda",options:["derivada","elástica directa","institucional"]},{label:"Mercado",options:["consumo","negocios","gubernamental"]},{label:"Efecto esperado",options:["demanda estable","caída amplificada","sin relación"]}],answer:["derivada","negocios","caída amplificada"],explanation:"La demanda de componentes deriva de la demanda final y puede fluctuar con mayor intensidad."},
 choice("c6-2","negocios6","Situación de compra","Una clínica recompra mensualmente el mismo insumo al proveedor aprobado, sin modificar especificaciones.",["Recompra directa","Recompra modificada","Tarea nueva","Compra gubernamental"],0,"La recompra directa es rutinaria y suele automatizarse con proveedores aprobados."),
 choice("c6-3","negocios6","Cuando cambia la especificación","Una fábrica mantiene la categoría de equipamiento, pero exige menor consumo energético y reabre la evaluación de proveedores.",["Recompra directa","Recompra modificada","Tarea nueva","Compra personal"],1,"Cambiar especificaciones o condiciones transforma la operación en una recompra modificada."),
 {id:"c6-4",module:"negocios6",type:"text",title:"Boeing y la venta de alto riesgo",context:"La compra de 50 aviones involucra años de análisis, múltiples especialistas, simulaciones y una relación de largo plazo.",prompt:"Expliquen tres diferencias decisivas frente a la compra de un pasaje aéreo por un consumidor.",rubric:["Unidad de compra profesional","Proceso formal y complejo","Relación comprador-vendedor"],explanation:"El mercado B2B concentra compradores, profesionaliza la compra y formaliza decisiones de alto riesgo."},
 {id:"c6-5",module:"compras6",type:"matrix",title:"¿Quién hace qué en el centro de compras?",context:"En un hospital, médicos especifican prestaciones, sistemas filtra compatibilidad y finanzas autoriza el contrato.",fields:[{label:"Médicos",options:["usuarios/influyentes","guardianes","compradores"]},{label:"Sistemas",options:["decisor","guardián/influyente","usuario final"]},{label:"Finanzas",options:["iniciador","decisor/aprobador","usuario"]}],answer:["usuarios/influyentes","guardián/influyente","decisor/aprobador"],explanation:"El centro de compras reúne roles diferentes; una misma persona puede ocupar más de uno."},
 {id:"c6-6",module:"compras6",type:"allocation",title:"Comité de compra B2B",context:"Una universidad evalúa una plataforma educativa para cinco años.",options:["Adecuación técnica","Costo total y riesgo","Soporte y relación"],answer:0,prompt:"Distribuyan 100 puntos de ponderación entre los criterios del pliego.",explanation:"La decisión organizacional combina criterios económicos, técnicos, de servicio y relacionales."},
 {id:"c6-7",module:"compras6",type:"text",title:"Especificación de necesidades",context:"Una empresa detecta fallas de coordinación y considera adquirir una plataforma colaborativa al estilo Cisco.",prompt:"Redacten una especificación general de necesidades sin mencionar marcas ni soluciones predeterminadas.",rubric:["Define el problema","Incluye resultados medibles","Evita sesgo hacia un proveedor"],explanation:"Definir necesidades antes de especificar productos mejora la evaluación de alternativas."},
 choice("c6-8","compras6","E-procurement: beneficio y riesgo","Una organización migra licitaciones rutinarias a una plataforma electrónica.",["Sólo reduce personal","Amplía acceso y eficiencia, pero exige controles de seguridad","Elimina la negociación y todo riesgo","Convierte la compra B2B en consumo"],1,"La adquisición electrónica reduce costos y acelera procesos, pero introduce riesgos de seguridad y dependencia."),
 {id:"c6-9",module:"compras6",type:"text",title:"Mercado gubernamental bajo restricciones",context:"Un municipio debe comprar equipamiento con presupuesto limitado, transparencia pública y procedimientos formales.",prompt:"Propongan una estrategia del proveedor que cree valor sin vulnerar igualdad, trazabilidad ni competencia.",rubric:["Respeta procedimiento formal","Explicita costo total","Ofrece evidencia verificable"],explanation:"Los mercados gubernamentales exigen documentación, transparencia y atención al costo total y al interés público."}
);

export const cards=[
 ["Capítulo 3","Red de transferencia de valor","Empresa, proveedores, distribuidores y clientes colaboran para mejorar el desempeño de todo el sistema de entrega de valor."],
 ["Capítulo 3","Públicos estratégicos","Grupos con interés o impacto real o potencial: financieros, medios, gobierno, ciudadanía, locales, general e internos."],
 ["Capítulo 3","Marketing de valor","Combinación de calidad y servicio a un precio justo, especialmente relevante cuando cae el poder adquisitivo."],
 ["Capítulo 3","Sustentabilidad ambiental","Estrategias, tecnologías y prácticas que el planeta puede sostener de manera indefinida."],
 ["Capítulo 3","Postura proactiva","La empresa intenta influir sobre su entorno mediante alianzas, relaciones públicas y otras acciones legítimas."],
 ["Capítulo 3","Marketing con causa","Vincula compras con una causa; debe crear valor auténtico y evitar la explotación oportunista."],
 ["Capítulo 4","Customer insight","Comprensión profunda y accionable de necesidades y conductas obtenida al transformar datos en conocimiento."],
 ["Capítulo 4","Sistema MIS","Personas y procedimientos que evalúan necesidades, recopilan información y distribuyen hallazgos útiles."],
 ["Capítulo 4","Investigación causal","Diseño para probar relaciones de causa y efecto mediante comparación y control de factores externos."],
 ["Capítulo 4","Etnografía de mercado","Observación cualitativa del consumidor en su contexto para descubrir necesidades no verbalizadas."],
 ["Capítulo 4","Data warehouse y mining","Consolidación de datos y análisis de patrones de compra, relaciones y señales predictivas."],
 ["Capítulo 4","Chief Privacy Officer","Responsable de la gobernanza y protección de datos personales y del cumplimiento ético y regulatorio."],
 ["Capítulo 5","Caja negra del comprador","Características del comprador y proceso de decisión que transforman estímulos en respuestas observables."],
 ["Capítulo 5","Grupos de referencia","Grupos que funcionan como puntos de comparación e influyen directa o indirectamente en actitudes y conductas."],
 ["Capítulo 5","Estilo de vida","Patrón de vida expresado en actividades, intereses y opiniones; va más allá de la clase social o personalidad."],
 ["Capítulo 5","Autoconcepto","Las posesiones contribuyen a la identidad: somos y expresamos parte de lo que consumimos."],
 ["Capítulo 5","Disonancia cognoscitiva","Incomodidad posterior a la compra causada por conflicto o dudas frente a las desventajas de la elección."],
 ["Capítulo 5","Difusión de innovaciones","Proceso por el que una idea o producto nuevo se extiende entre los miembros de un sistema social."],
 ["Capítulo 6","Demanda derivada","La demanda industrial proviene, en última instancia, de la demanda de bienes y servicios de consumo."],
 ["Capítulo 6","Centro de compras","Conjunto de participantes que comparten roles de iniciador, usuario, influyente, comprador, decisor y guardián."],
 ["Capítulo 6","Recompra directa","Situación rutinaria en la que se vuelve a ordenar sin modificaciones relevantes."],
 ["Capítulo 6","Recompra modificada","El comprador desea cambiar especificaciones, precios, condiciones o proveedores."],
 ["Capítulo 6","Tarea nueva","Compra por primera vez que exige más información, participantes y deliberación."],
 ["Capítulo 6","Adquisición electrónica","Compra organizacional en línea que mejora eficiencia y acceso, con riesgos de seguridad y dependencia."]
].map((x,i)=>({id:`c${i+1}`,tag:x[0],title:x[1],text:x[2]}));

// Mecánicas específicas: el contenido no se reduce a selección única.
const envKeys={
 e1:["macro","político-legal","adaptación"],e2:["micro","intermediarios","negociación"],
 e3:["macro","demográfico","innovación"],e4:["micro","público financiero","negociación"],
 e5:["macro","natural","innovación"],e6:["micro","competidores","innovación"]
};
activities.filter(a=>a.module==="entorno").forEach(a=>Object.assign(a,{type:"matrix",fields:[
 {label:"Ámbito",options:["micro","macro"]},
 {label:"Factor / actor",options:["intermediarios","público financiero","competidores","político-legal","demográfico","natural","tecnológico"]},
 {label:"Postura gerencial",options:["negociación","adaptación","innovación"]}
],answer:envKeys[a.id]}));

Object.assign(activities.find(a=>a.id==="i1"),{type:"sequence",steps:["Explorar ocasiones de uso","Formular hipótesis de canibalización","Experimentar en plazas comparables"],answer:[0,1,2]});
Object.assign(activities.find(a=>a.id==="i4"),{type:"text",prompt:"Reescriban la pregunta de manera neutral y con una escala equilibrada.",rubric:["No anticipa superioridad","Evita adjetivos valorativos","Incluye opciones equilibradas"]});
activities.filter(a=>a.module==="directorio").forEach(a=>Object.assign(a,{type:"allocation",prompt:"Distribuyan 100 puntos de apoyo del directorio entre los planes y defiendan la asignación."}));
activities.filter(a=>/^(c5|c6)-/.test(a.id)&&!a.options).forEach(a=>a.options=["Producción del equipo"]);
