import{initializeApp}from"https://www.gstatic.com/firebasejs/11.2.0/firebase-app.js";
import{getAuth,signInWithEmailAndPassword,signInAnonymously,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/11.2.0/firebase-auth.js";
import{getFirestore,doc,getDoc,setDoc,collection,onSnapshot,serverTimestamp}from"https://www.gstatic.com/firebasejs/11.2.0/firebase-firestore.js";
const config={apiKey:"AIzaSyDomTdNBjbxc7TC0u8RDTA1OVMM-760hRM",authDomain:"tallertooi.firebaseapp.com",projectId:"tallertooi",appId:"1:346593558589:web:dc74d05690cc40aa092a54"};
const app=initializeApp(config,"marketing-kotler"),auth=getAuth(app),db=getFirestore(app),KEY="comercializacion-kotler-full-room",nativeSet=localStorage.setItem.bind(localStorage);
let applying=false,currentCode=null,main={},members={},responses={},unsubs=[];const ready=new Promise(resolve=>onAuthStateChanged(auth,resolve));
function publishLocal(){if(!currentCode||!main.code)return;applying=true;nativeSet(KEY,JSON.stringify({...main,members,responses}));window.dispatchEvent(new StorageEvent("storage",{key:KEY}));applying=false}
function watch(code){if(currentCode===code)return;unsubs.forEach(x=>x());unsubs=[];currentCode=code;unsubs.push(onSnapshot(doc(db,"marketingSessions",code),s=>{if(!s.exists())return;main=s.data();publishLocal()}));unsubs.push(onSnapshot(collection(db,"marketingSessions",code,"participants"),s=>{members={};s.forEach(d=>members[d.id]=d.data());publishLocal()}));unsubs.push(onSnapshot(collection(db,"marketingSessions",code,"responses"),s=>{responses={};s.forEach(d=>{const x=d.data();responses[x.localKey]=x});publishLocal()}))}
async function persist(oldRoom,next){const user=auth.currentUser;if(!user||!next?.code)return;watch(next.code);if(!user.isAnonymous){const {members:_m,responses:_r,...room}=next;await setDoc(doc(db,"marketingSessions",next.code),{...room,ownerId:user.uid,updatedAt:serverTimestamp()},{merge:true});await setDoc(doc(db,"marketingSessions",next.code,"participants",user.uid),{name:Object.values(next.members||{}).find(x=>x.role==="teacher")?.name||"Docente",role:"teacher",updatedAt:serverTimestamp()},{merge:true});return}const oldResponses=oldRoom?.responses||{};for(const [key,value]of Object.entries(next.responses||{}))if(JSON.stringify(oldResponses[key])!==JSON.stringify(value))await setDoc(doc(db,"marketingSessions",next.code,"responses",`${value.item}_${value.round}_${user.uid}`),{...value,localKey:key,participantId:user.uid,updatedAt:serverTimestamp()});const oldNames=Object.values(oldRoom?.members||{}).map(x=>x.name),team=Object.values(next.members||{}).find(x=>x.role==="team"&&!oldNames.includes(x.name));if(team)await setDoc(doc(db,"marketingSessions",next.code,"participants",user.uid),{...team,updatedAt:serverTimestamp()},{merge:true})}
localStorage.setItem=function(key,value){const old=key===KEY?JSON.parse(localStorage.getItem(KEY)||"null"):null;nativeSet(key,value);if(key===KEY&&!applying)persist(old,JSON.parse(value)).catch(console.error)};
export async function loginTeacher(email,password){await signInWithEmailAndPassword(auth,email,password);return auth.currentUser}
export async function loadStudentRoom(code){await ready;if(!auth.currentUser||!auth.currentUser.isAnonymous)await signInAnonymously(auth);const snap=await getDoc(doc(db,"marketingSessions",code));if(!snap.exists())throw new Error("No encontramos una sala con ese código.");main=snap.data();currentCode=null;watch(code);nativeSet(KEY,JSON.stringify({...main,members:{},responses:{}}));return main}
export function firebaseError(error){const code=error?.code||"";if(code.includes("invalid-credential")||code.includes("wrong-password"))return"Correo o contraseña incorrectos.";if(code.includes("user-not-found"))return"No existe una cuenta docente con ese correo.";if(code.includes("operation-not-allowed"))return"El acceso requerido no está habilitado en Firebase.";return error?.message||"No se pudo conectar con Firebase."}
