import {activities} from "./catalog.js";
const KEY="comercializacion-kotler-full-room";
let busy=false;
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function state(){return JSON.parse(localStorage.getItem(KEY)||"null")}
function item(r){const list=activities.filter(a=>a.module===r.module);return list[r.positions[r.module]||0]}
function identity(){const text=document.querySelector(".brand small")?.textContent||"";return text.startsWith("Equipo ")?text.slice(7):null}
function mechanics(a,disabled){
 if(a.type==="matrix")return `<div class="mechanic matrix-mechanic"><div class="mechanic-title">Construyan el vector completo</div><div class="matrix-fields">${a.fields.map((f,i)=>`<label><span>${i+1}. ${f.label}</span><select data-matrix="${i}" ${disabled?"disabled":""}><option value="">Seleccionar…</option>${f.options.map(o=>`<option>${o}</option>`).join("")}</select></label>`).join("")}</div><button class="btn" data-varied-submit="matrix" ${disabled?"disabled":""}>Emitir dictamen del equipo</button></div>`;
 if(a.type==="sequence")return `<div class="mechanic"><div class="mechanic-title">Ordenen el diseño de investigación</div><p class="context">Asignen una etapa a cada posición del proceso.</p><div class="sequence-fields">${[1,2,3].map((n,i)=>`<label><span>Etapa ${n}</span><select data-sequence="${i}" ${disabled?"disabled":""}><option value="">Seleccionar…</option>${a.steps.map((s,j)=>`<option value="${j}">${s}</option>`).join("")}</select></label>`).join("")}</div><button class="btn" data-varied-submit="sequence" ${disabled?"disabled":""}>Enviar secuencia</button></div>`;
 if(a.type==="text")return `<div class="mechanic"><div class="mechanic-title">Taller de instrumento</div><p>${a.prompt}</p><textarea id="open-answer" placeholder="Escriban aquí la versión neutral…" ${disabled?"disabled":""}></textarea><div class="rubric">${a.rubric.map(x=>`<span>✓ ${x}</span>`).join("")}</div><button class="btn" data-varied-submit="text" ${disabled?"disabled":""}>Publicar reformulación</button></div>`;
 if(a.type==="allocation")return `<div class="mechanic"><div class="mechanic-title">Mesa de asignación estratégica</div><p class="context">${a.prompt}</p><div class="allocation">${a.options.map((o,i)=>`<label><span><b>Plan ${String.fromCharCode(65+i)}</b> ${o}</span><div><input type="range" min="0" max="100" step="5" value="0" data-allocation="${i}" ${disabled?"disabled":""}><output>0</output></div></label>`).join("")}</div><div class="allocation-total">Total asignado: <b>0</b> / 100</div><button class="btn" data-varied-submit="allocation" ${disabled?"disabled":""}>Presentar al directorio</button></div>`;
 return null;
}
function enhance(){if(busy)return;const r=state(),caseEl=document.querySelector(".case");if(!r||!caseEl||r.status==="lobby"||r.module==="tarjetas")return;const a=item(r);if(!a||["choice","number"].includes(a.type)||caseEl.dataset.varied===a.id)return;busy=true;caseEl.dataset.varied=a.id;const teacher=!identity(),disabled=teacher||r.revealed;const target=caseEl.querySelector(".number-task,.option-list");if(target)target.outerHTML=mechanics(a,disabled);const feedback=caseEl.querySelector(".feedback");if(feedback&&a.type==="text")feedback.innerHTML=`<b>Criterios de revisión</b><br>${a.rubric.join(" · ")}`;const rs=Object.values(r.responses).filter(x=>x.item===a.id&&x.round===r.round),panels=document.querySelectorAll(".stage > .panel"),panel=panels[panels.length-1];if(panel)panel.innerHTML=`<span class="tag">Producciones colectivas · ${rs.length}</span>${rs.length?`<div class="response-wall">${rs.map(x=>`<article><b>${esc(x.team)}</b><p>${format(x.value,a.type)}</p>${x.reason?`<small>${esc(x.reason)}</small>`:""}</article>`).join("")}</div>`:`<p class="context">Todavía no hay entregas de equipos.</p>`}`;busy=false}
function format(v,type){if(type==="matrix")return esc(v.join(" · "));if(type==="sequence")return v.map((x,i)=>`${i+1}. ${esc(x)}`).join(" → ");if(type==="allocation")return v.map((n,i)=>`${String.fromCharCode(65+i)}: ${n}%`).join(" · ");return esc(v)}
new MutationObserver(enhance).observe(document.querySelector("#app"),{childList:true,subtree:true});enhance();
document.addEventListener("input",e=>{if(e.target.matches("[data-allocation]")){e.target.nextElementSibling.textContent=e.target.value;const vals=[...document.querySelectorAll("[data-allocation]")].map(x=>Number(x.value)),total=vals.reduce((a,b)=>a+b,0);document.querySelector(".allocation-total b").textContent=total}},true);
document.addEventListener("click",e=>{const btn=e.target.closest("[data-varied-submit]");if(!btn)return;e.preventDefault();e.stopImmediatePropagation();const r=state(),a=item(r),team=identity();if(!team)return;let value;if(btn.dataset.variedSubmit==="matrix"){value=[...document.querySelectorAll("[data-matrix]")].map(x=>x.value);if(value.some(x=>!x))return}else if(btn.dataset.variedSubmit==="sequence"){const ids=[...document.querySelectorAll("[data-sequence]")].map(x=>Number(x.value));if(new Set(ids).size!==ids.length)return;value=ids.map(i=>a.steps[i])}else if(btn.dataset.variedSubmit==="text"){value=document.querySelector("#open-answer").value.trim();if(!value)return}else{value=[...document.querySelectorAll("[data-allocation]")].map(x=>Number(x.value));if(value.reduce((a,b)=>a+b,0)!==100){document.querySelector(".allocation-total").classList.add("invalid");return}}const reason=document.querySelector("#reason")?.value.trim()||"",key=`${team}-${a.id}-${r.round}`;r.responses[key]={team,item:a.id,round:r.round,value,reason};localStorage.setItem(KEY,JSON.stringify(r));window.dispatchEvent(new StorageEvent("storage",{key:KEY}));},true);
